version: "3"
services:
    mongodb:
      container_name: mongocontainer
      image: mongo:3.6
      environment:
        - MONGO_DATA_DIR=/otus29
      volumes:
        - ./otus29:/otus29
      ports:
          - 27017:27017
    app:
      image: otus29:1.0
      ports:
        - 8080:8080